import './globals.scss'
import { Inter } from 'next/font/google'
import {ClerkProvider} from "@clerk/nextjs";
import {ReactNode} from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
